kind: pipeline
type: docker
name: react-app-example

clone:
  depth: 50

steps:
  - name: install
    image: node:18.14-buster
    # environment:
    #   SSH_KEY:
    #     from_secret: bitbucket_ssh_key
    commands:
      # - mkdir /root/.ssh
      # - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
      # - chmod 600 /root/.ssh/id_rsa
      # - ssh-keyscan -t rsa bitbucket.org > /root/.ssh/known_hosts
      - corepack enable
      - yarn install --silent --immutable
    when:
      branch:
        - master
        - develop
        - release/*
  - name: unit-test
    image: node:18.14-buster
    commands:
      - yarn test
    when:
      branch:
        - master
        - develop
        - release/*
  - name: release
    image: node:18.14-buster
    environment:
      GIT_AUTHOR_NAME: ${DRONE_COMMIT_AUTHOR_NAME}
      GIT_AUTHOR_EMAIL: ${DRONE_COMMIT_AUTHOR_EMAIL}
      GIT_COMMITTER_NAME: ${DRONE_COMMIT_AUTHOR_NAME}
      GIT_COMMITTER_EMAIL: ${DRONE_COMMIT_AUTHOR_EMAIL}
      GIT_CREDENTIALS:
        from_secret: bitbucket_app_password
    commands:
      - npx semantic-release
    when:
      branch:
        - master
        - release/*
      event:
        - push
  - name: publish
    image: plugins/docker
    # environment:
    #   SSH_KEY:
    #     from_secret: bitbucket_ssh_key
    settings:
      repo: cicd-so-happy.maxwin.com.tw:5000/react-app-example
      registry: cicd-so-happy.maxwin.com.tw:5000
      tags: ${DRONE_TAG}
      insecure: true
      # build_args_from_env:
      #   - SSH_KEY
      target: publish
    when:
      ref:
        - refs/tags/*
