yarnPath: .yarn/releases/yarn-3.5.0.cjs
nodeLinker: node-modules
packageExtensions:
  'eslint-config-react-app@*':
    dependencies:
      '@babel/plugin-syntax-flow': '*'
      '@babel/plugin-transform-react-jsx': '*'